version: appveyor-{build}
configuration: Release
platform:
 - x86
 - x64
clone_folder: C:\Haltroy\Korot-appveyor\
only_commits:
 message: /AppVeyorBuild/
before_build:
 - cmd: nuget restore
build:
  project: Korot Desktop/Korot Desktop.csproj
artifacts:
- path: /Korot Desktop\bin/
  name: AppveyorLatestBuild-Desktop-x64